name: weavingjeans
reference: main
build_opts:
  force_image_pull: true
  no_cache: true
  quiet: false
  args:
profiles:
  - prod
external_secrets:
  PORT: c1718f70-5758-4192-8e45-10993496acb9:prod:PORT
